# SPDX-License-Identifier: AGPL-3.0-only WITH OzmaPluginException
"""
Ozma routing graph — Phase 1 + Phase 2.

Phase 1: observational graph model (device/port/link).
Phase 2: intent system, bindings, pipeline primitives, routing engine.
"""

from .model import (
    InfoQuality,
    Location,
    PhysicalLocation,
    HardwareIdentity,
    BandwidthSpec,
    LatencySpec,
    JitterSpec,
    LossSpec,
    ActivationTimeSpec,
    PortState,
    LinkState,
    PortRef,
    Device,
    Port,
    Link,
    DeviceType,
    MediaType,
    PortDirection,
    LinkStatus,
)
from .graph import RoutingGraph
from .builder import GraphBuilder
from .intent import (
    Constraints,
    Preferences,
    DegradationPolicy,
    StreamIntent,
    Intent,
    BUILTIN_INTENTS,
    compose_intents,
    EncryptionRequirement,
    VideoStrategy,
    AudioStrategy,
    HidStrategy,
)
from .binding import (
    BindingCondition,
    BindingScope,
    RevertPolicy,
    IntentBinding,
    BindingRegistry,
    ConditionOp,
    ConditionMode,
    ConditionSource,
    RevertMode,
    StateResolver,
    DictStateResolver,
)
from .pipeline import (
    Pipeline,
    PipelineHop,
    PipelineMetrics,
    PipelineState,
    WarmthPolicy,
    WarmCost,
    FormatRef,
    LinkRef,
    ConversionRef,
)
from .router import Router
from .transport_plugin import (
    ChannelPriority,
    FlowControl,
    Channel,
    ChannelStats,
    RekeyPolicy,
    MultiplexedConnection,
    ConnectionState,
    LinkMetrics,
    StreamHandle,
    TransportCharacteristics,
    TransportPlugin,
    TransportRegistry,
    TRANSPORT_CHARACTERISTICS,
    get_transport_characteristics,
    BluetoothProfile,
    BluetoothCodecInfo,
    BluetoothConnection,
    BluetoothLinkState,
    WiFiSignalQuality,
    WiFiLinkRate,
    WiFiLinkState,
    SerialProtocol,
    SerialLinkState,
)
from .monitoring import (
    StateChangeType,
    StateChangeRecord,
    JournalRetention,
    JournalPolicy,
    MonitoringJournal,
    TrendAlertType,
    TrendAlert,
    TrendAlertManager,
    MetricRetention,
    MetricPoint,
    MetricSeries,
    MetricStore,
)
from .measurement import (
    QualifiedValue,
    StalenessAction,
    StalenessPolicy,
    RefreshCost,
    RefreshClass,
    ClassFreshness,
    DeviceFreshness,
    MeasurementStore,
    STANDARD_REFRESH_CLASSES,
    get_refresh_class,
)
from .measurement_engine import MeasurementEngine
from .formats import (
    VideoFormat,
    AudioFormat,
    HidFormat,
    ScreenFormat,
    RgbFormat,
    ControlFormat,
    ControlInputSet,
    ControlOutputSet,
    DataFormat,
    DataSchema,
    DataField,
    Format,
    FormatRange,
    FormatSet,
    NumericRange,
    NegotiationFailure,
    enumerate_formats,
    restrict_formats,
    fixate_format,
    negotiate_format,
    video_bandwidth_uncompressed,
    audio_bandwidth_uncompressed,
    hid_bandwidth,
    screen_bandwidth_raw,
    rgb_bandwidth,
    serial_bandwidth_bytes_per_sec,
)

__all__ = [
    # Phase 1 — graph model
    "InfoQuality",
    "Location",
    "PhysicalLocation",
    "HardwareIdentity",
    "BandwidthSpec",
    "LatencySpec",
    "JitterSpec",
    "LossSpec",
    "ActivationTimeSpec",
    "PortState",
    "LinkState",
    "PortRef",
    "Device",
    "Port",
    "Link",
    "DeviceType",
    "MediaType",
    "PortDirection",
    "LinkStatus",
    "RoutingGraph",
    "GraphBuilder",
    # Phase 2 — intent system
    "Constraints",
    "Preferences",
    "DegradationPolicy",
    "StreamIntent",
    "Intent",
    "BUILTIN_INTENTS",
    "compose_intents",
    "EncryptionRequirement",
    "VideoStrategy",
    "AudioStrategy",
    "HidStrategy",
    # Phase 2 — bindings
    "BindingCondition",
    "BindingScope",
    "RevertPolicy",
    "IntentBinding",
    "BindingRegistry",
    "ConditionOp",
    "ConditionMode",
    "ConditionSource",
    "RevertMode",
    "StateResolver",
    "DictStateResolver",
    # Phase 2 — pipeline
    "Pipeline",
    "PipelineHop",
    "PipelineMetrics",
    "PipelineState",
    "WarmthPolicy",
    "WarmCost",
    "FormatRef",
    "LinkRef",
    "ConversionRef",
    # Phase 2 — router
    "Router",
    # Phase 3 — format system
    "VideoFormat",
    "AudioFormat",
    "HidFormat",
    "ScreenFormat",
    "RgbFormat",
    "ControlFormat",
    "ControlInputSet",
    "ControlOutputSet",
    "DataFormat",
    "DataSchema",
    "DataField",
    "Format",
    "FormatRange",
    "FormatSet",
    "NumericRange",
    "NegotiationFailure",
    "enumerate_formats",
    "restrict_formats",
    "fixate_format",
    "negotiate_format",
    "video_bandwidth_uncompressed",
    "audio_bandwidth_uncompressed",
    "hid_bandwidth",
    "screen_bandwidth_raw",
    "rgb_bandwidth",
    "serial_bandwidth_bytes_per_sec",
    # Phase 6 — monitoring, journal, trend alerts, metric time series
    "StateChangeType",
    "StateChangeRecord",
    "JournalRetention",
    "JournalPolicy",
    "MonitoringJournal",
    "TrendAlertType",
    "TrendAlert",
    "TrendAlertManager",
    "MetricRetention",
    "MetricPoint",
    "MetricSeries",
    "MetricStore",
    # Phase 5 — active measurement + quality decay
    "QualifiedValue",
    "StalenessAction",
    "StalenessPolicy",
    "RefreshCost",
    "RefreshClass",
    "ClassFreshness",
    "DeviceFreshness",
    "MeasurementStore",
    "STANDARD_REFRESH_CLASSES",
    "get_refresh_class",
    "MeasurementEngine",
    # Phase 4 — transport plugin interface
    "ChannelPriority",
    "FlowControl",
    "Channel",
    "ChannelStats",
    "RekeyPolicy",
    "MultiplexedConnection",
    "ConnectionState",
    "LinkMetrics",
    "StreamHandle",
    "TransportCharacteristics",
    "TransportPlugin",
    "TransportRegistry",
    "TRANSPORT_CHARACTERISTICS",
    "get_transport_characteristics",
    "BluetoothProfile",
    "BluetoothCodecInfo",
    "BluetoothConnection",
    "BluetoothLinkState",
    "WiFiSignalQuality",
    "WiFiLinkRate",
    "WiFiLinkState",
    "SerialProtocol",
    "SerialLinkState",
]
