#!/usr/bin/env python3
"""
Apply Configuration from First-Boot Wizard

Applies all settings configured during the wizard.
"""

import os
import sys
import json
import subprocess
from pathlib import Path
from typing import Any


def run_command(cmd: list[str], check: bool = True, capture: bool = True) -> subprocess.CompletedProcess:
    """Run a command with optional checking."""
    if capture:
        result = subprocess.run(cmd, capture_output=True, text=True)
    else:
        result = subprocess.run(cmd)
    
    if check and result.returncode != 0:
        raise RuntimeError(f"Command failed: {' '.join(cmd)}\n{result.stderr}")
    
    return result


def apply_network(config: dict[str, Any]) -> None:
    """Apply network configuration."""
    mode = config.get("mode", "dhcp")
    
    if mode == "dhcp":
        # Generate netplan config for DHCP
        netplan = """network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: true
"""
    else:
        # Static IP configuration
        static = config.get("static", {})
        ip = static.get("ip", "")
        gateway = static.get("gateway", "")
        dns = static.get("dns", "")
        
        netplan = f"""network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: false
      addresses:
        - {ip}/24
      gateway4: {gateway}
      nameservers:
        addresses:
          - {dns}
"""
    
    # Write netplan config
    Path("/etc/netplan/01-ozmaos.yaml").write_text(netplan)
    run_command(["chmod", "600", "/etc/netplan/01-ozmaos.yaml"])
    
    # Apply netplan
    run_command(["netplan", "apply"])


def apply_hostname(config: dict[str, Any]) -> None:
    """Set system hostname."""
    hostname = config.get("hostname", "ozma")
    
    # Set hostname immediately
    run_command(["hostname", hostname])
    
    # Update /etc/hostname
    Path("/etc/hostname").write_text(hostname + "\n")
    
    # Update /etc/hosts
    hosts_content = """127.0.0.1   localhost
127.0.1.1   {hostname}

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
""".format(hostname=hostname)
    
    Path("/etc/hosts").write_text(hosts_content)


def apply_timezone(config: dict[str, Any]) -> None:
    """Set system timezone."""
    timezone = config.get("timezone", "UTC")
    run_command(["timedatectl", "set-timezone", timezone])


def apply_user(config: dict[str, Any]) -> None:
    """Create admin user."""
    username = config.get("username", "admin")
    password = config.get("password", "")
    
    # Create user if not exists
    try:
        run_command(["id", username], check=False)
        user_exists = True
    except:
        user_exists = False
    
    if not user_exists:
        # Create user with home directory
        run_command([
            "useradd",
            "-m",
            "-s", "/bin/bash",
            "-G", "sudo,docker,libvirtd",
            username
        ])
    
    # Set password
    run_command(["chpasswd"], check=False)
    proc = subprocess.Popen(
        ["chpasswd"],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True
    )
    proc.communicate(input=f"{username}:{password}")
    
    # Grant sudo NOPASSWD for the user
    sudoers_entry = f"{username} ALL=(ALL) NOPASSWD:ALL\n"
    Path("/etc/sudoers.d/ozmaos-user").write_text(sudoers_entry)
    run_command(["chmod", "440", "/etc/sudoers.d/ozmaos-user"])


def apply_services(service_names: list[str], hardware: dict[str, Any]) -> None:
    """Enable and start selected services."""
    import services
    
    # Get service definitions
    available = services.get_available_services(hardware)
    
    for name in service_names:
        if name not in available:
            continue
        
        service_info = services.SERVICES[name]
        
        # Enable Docker Compose services
        if service_info.get("docker_compose"):
            # Check if Docker Compose file exists
            compose_file = Path(f"/opt/ozmaos/compose/{name}/docker-compose.yml")
            if compose_file.exists():
                # Copy compose file to docker-compose directory
                dest_dir = Path("/etc/ozmaos/compose")
                dest_dir.mkdir(parents=True, exist_ok=True)
                
                # Create override compose file
                override_file = dest_dir / f"{name}.yml"
                override_content = f"""# Auto-generated by OzmaOS first-boot wizard
services:
  {name}:
    restart: unless-stopped
    labels:
      - ozmaos.managed=true
"""
                override_file.write_text(override_content)
                
                # Pull and start service
                subprocess.run(
                    ["docker-compose", "-f", str(compose_file), "-f", str(override_file), 
                     "pull", "-q"],
                    capture_output=True, timeout=120
                )
                subprocess.run(
                    ["docker-compose", "-f", str(compose_file), "-f", str(override_file), 
                     "up", "-d"],
                    capture_output=True, timeout=120
                )
        
        # Enable systemd services
        for systemd_unit in service_info.get("systemd", []):
            run_command(["systemctl", "enable", systemd_unit], check=False)
            run_command(["systemctl", "start", systemd_unit], check=False)


def apply_zfs(config: dict[str, Any]) -> None:
    """Create ZFS pool if configured."""
    if not config.get("enabled", False):
        return
    
    mode = config.get("mode", "skip")
    disks = config.get("disks", [])
    
    if mode == "skip" or not disks:
        return
    
    pool_name = "storage"
    
    if mode == "mirror":
        # Mirror requires exactly 2 disks
        if len(disks) >= 2:
            disk_list = " ".join(disks[:2])
            run_command(["zpool", "create", "-f", pool_name, "mirror", disk_list])
    
    elif mode == "raidz1":
        # RAIDZ1 requires at least 3 disks
        if len(disks) >= 3:
            disk_list = " ".join(disks[:3])
            run_command(["zpool", "create", "-f", pool_name, "raidz1", disk_list])
        elif len(disks) == 2:
            # Fall back to mirror with 2 disks
            disk_list = " ".join(disks[:2])
            run_command(["zpool", "create", "-f", pool_name, "mirror", disk_list])
    
    # Set default mount point
    run_command(["zfs", "set", f"mountpoint=/mnt/{pool_name}", pool_name], check=False)
    run_command(["zfs", "set", "atime=off", pool_name], check=False)
    
    # Update fstab to mount on boot
    Path("/etc/fstab").open("a").write(f"{pool_name} /mnt/{pool_name} zfs defaults 0 0\n")


def apply_connect(config: dict[str, Any]) -> None:
    """Connect to Ozma Connect."""
    if not config.get("enabled", False):
        return
    
    email = config.get("email", "")
    password = config.get("password", "")
    
    if not email or not password:
        return
    
    # Run ozma connect link
    try:
        subprocess.run(
            ["ozma", "connect", "link", "--email", email],
            input=password + "\n",
            capture_output=True,
            timeout=60,
            text=True
        )
    except Exception as e:
        print(f"Warning: Failed to connect to Ozma Connect: {e}", flush=True)


def apply(config: dict[str, Any], hardware: dict[str, Any]) -> None:
    """Apply all configuration."""
    print("Applying configuration...", flush=True)
    
    # Apply in order
    if "network" in config:
        print("  - Applying network configuration...", flush=True)
        apply_network(config["network"])
    
    if "hostname" in config:
        print("  - Setting hostname...", flush=True)
        apply_hostname(config["hostname"])
    
    if "timezone" in config:
        print("  - Setting timezone...", flush=True)
        apply_timezone(config["timezone"])
    
    if "admin_user" in config:
        print("  - Creating admin user...", flush=True)
        apply_user(config["admin_user"])
    
    if "services" in config:
        print("  - Enabling services...", flush=True)
        apply_services(config["services"], hardware)
    
    if "zfs" in config:
        print("  - Creating ZFS pool...", flush=True)
        apply_zfs(config["zfs"])
    
    if "connect" in config:
        print("  - Connecting to Ozma Connect...", flush=True)
        apply_connect(config["connect"])
    
    print("Configuration complete!", flush=True)


if __name__ == "__main__":
    # Load config from JSON if provided as argument
    if len(sys.argv) > 1:
        config_file = Path(sys.argv[1])
        config = json.loads(config_file.read_text())
        
        import detect_hardware
        hw = detect_hardware.detect()
        
        apply(config, hw)
    else:
        print("Usage: apply_config.py <config.json>")
        sys.exit(1)
