# SPDX-License-Identifier: AGPL-3.0-only WITH OzmaPluginException
"""
Automated screenshot documentation — generate SOPs from system interaction.

Runs an automation script, captures a screenshot at each step, OCRs the
screen text, and generates a Markdown document with annotated screenshots.

Use cases:
  - Document a BIOS configuration procedure
  - Create an installation guide from an actual installation
  - Generate compliance evidence (screenshots of security settings)
  - Build training materials from real system interaction

Output:
  Markdown file with:
    ## Step 1: [action description]
    ![Screenshot](screenshots/step_001.png)
    Screen text: "BIOS Setup Utility - Boot Configuration"
    Action: Pressed F2 to enter BIOS

  Plus a directory of numbered screenshots.
"""

from __future__ import annotations

import asyncio
import json
import logging
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

log = logging.getLogger("ozma.auto_docs")

DOCS_DIR = Path(__file__).parent / "static" / "generated_docs"


@dataclass
class DocStep:
    """A single step in a generated document."""
    step_num: int
    action: str              # What was done ("Pressed Enter", "Typed 'hostname'")
    screen_text: str = ""    # OCR'd text at this step
    screenshot_path: str = ""
    timestamp: float = 0.0
    notes: str = ""


class AutoDocGenerator:
    """
    Generates documentation from automation script execution.

    Hooks into the automation engine to capture screenshots and OCR
    text at each step, then assembles a Markdown document.
    """

    def __init__(self, text_capture: Any = None, captures: Any = None) -> None:
        self._text_capture = text_capture
        self._captures = captures
        self._steps: list[DocStep] = []
        self._doc_id = ""
        self._recording = False

    @property
    def is_recording(self) -> bool:
        return self._recording

    def start_document(self, title: str = "Procedure") -> str:
        """Start recording steps for a new document."""
        self._doc_id = f"doc-{int(time.time())}"
        self._steps = []
        self._recording = True
        doc_dir = DOCS_DIR / self._doc_id / "screenshots"
        doc_dir.mkdir(parents=True, exist_ok=True)
        log.info("Auto-documentation started: %s", title)
        return self._doc_id

    def record_step(self, action: str, notes: str = "") -> None:
        """Record a step with current screen state."""
        if not self._recording:
            return

        step_num = len(self._steps) + 1
        screen_text = ""
        if self._text_capture and self._text_capture.last_result:
            screen_text = self._text_capture.last_result.text[:500]

        step = DocStep(
            step_num=step_num,
            action=action,
            screen_text=screen_text,
            timestamp=time.time(),
            notes=notes,
        )
        self._steps.append(step)

    def finish_document(self, title: str = "Procedure") -> str:
        """Stop recording and generate the Markdown document."""
        self._recording = False
        if not self._steps:
            return ""

        doc_dir = DOCS_DIR / self._doc_id
        md_lines = [
            f"# {title}",
            f"",
            f"Generated by Ozma Auto-Documentation on {time.strftime('%Y-%m-%d %H:%M')}",
            f"",
            f"---",
            f"",
        ]

        for step in self._steps:
            md_lines.append(f"## Step {step.step_num}: {step.action}")
            md_lines.append("")
            if step.screenshot_path:
                md_lines.append(f"![Step {step.step_num}]({step.screenshot_path})")
                md_lines.append("")
            if step.screen_text:
                md_lines.append("**Screen text:**")
                md_lines.append(f"```")
                md_lines.append(step.screen_text[:300])
                md_lines.append(f"```")
                md_lines.append("")
            if step.notes:
                md_lines.append(f"> {step.notes}")
                md_lines.append("")
            md_lines.append("---")
            md_lines.append("")

        md_text = "\n".join(md_lines)
        md_path = doc_dir / "procedure.md"
        md_path.write_text(md_text)

        log.info("Document generated: %s (%d steps)", self._doc_id, len(self._steps))
        return str(md_path)

    def list_documents(self) -> list[dict]:
        """List all generated documents."""
        if not DOCS_DIR.exists():
            return []
        docs = []
        for d in sorted(DOCS_DIR.iterdir(), reverse=True):
            if d.is_dir() and (d / "procedure.md").exists():
                docs.append({
                    "id": d.name,
                    "url": f"/generated_docs/{d.name}/procedure.md",
                    "size": (d / "procedure.md").stat().st_size,
                })
        return docs
