# SPDX-License-Identifier: AGPL-3.0-only WITH OzmaPluginException
"""
Vision providers — pluggable UI element detection backends.

Each provider takes a screenshot (PIL Image) and returns detected UI elements
with bounding boxes, types, and descriptions. The screen reader picks the
best available provider automatically.

Providers (in priority order):
  1. OmniParser   — Microsoft's YOLO + Florence-2 (best accuracy, needs GPU or Connect)
  2. YOLO UI      — Standalone ultralytics YOLO fine-tuned for UI elements
  3. Connect AI   — Remote inference via Ozma Connect (metered, any model)
  4. Heuristic    — Edge detection + OCR + rules (always available, no deps)

Set-of-Marks (SoM) overlay is generated by the screen reader from any
provider's output — it's not provider-specific.
"""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

log = logging.getLogger("ozma.vision")


@dataclass
class DetectedElement:
    """A UI element detected by a vision provider."""
    element_type: str       # button, text_field, icon, checkbox, link, menu, dialog, label, image
    text: str               # OCR text or description
    x: int                  # bounding box left
    y: int                  # bounding box top
    width: int              # bounding box width
    height: int             # bounding box height
    confidence: float = 0.0 # detection confidence 0-1
    description: str = ""   # AI-generated description (from Florence-2 or similar)
    clickable: bool = False # whether this element accepts clicks
    interactable: bool = False  # broader: clickable, typeable, checkable

    @property
    def center(self) -> tuple[int, int]:
        return (self.x + self.width // 2, self.y + self.height // 2)

    def to_dict(self) -> dict:
        return {
            "type": self.element_type,
            "text": self.text,
            "x": self.x, "y": self.y,
            "width": self.width, "height": self.height,
            "center": list(self.center),
            "confidence": round(self.confidence, 3),
            "description": self.description,
            "clickable": self.clickable,
            "interactable": self.interactable,
        }


@dataclass
class VisionResult:
    """Result from a vision provider."""
    elements: list[DetectedElement] = field(default_factory=list)
    provider: str = ""
    inference_ms: float = 0.0

    def to_dict(self) -> dict:
        return {
            "elements": [e.to_dict() for e in self.elements],
            "provider": self.provider,
            "inference_ms": round(self.inference_ms, 1),
        }


class VisionProvider(ABC):
    """Base class for vision providers."""

    @property
    @abstractmethod
    def name(self) -> str: ...

    @abstractmethod
    async def detect(self, image: Any) -> VisionResult:
        """Detect UI elements in a PIL Image."""
        ...

    @abstractmethod
    def available(self) -> bool:
        """Check if this provider is ready to use."""
        ...


# ── OmniParser provider ─────────────────────────────────────────────────────

class OmniParserProvider(VisionProvider):
    """
    Microsoft OmniParser v2 — YOLOv8 + Florence-2 + OCR.

    Best accuracy for UI element detection. Requires:
      - ultralytics (YOLO)
      - transformers + torch (Florence-2)
      - Model weights (auto-downloaded on first use)

    Can run on CPU (~2-5s per frame) or GPU (~200ms).
    """

    name = "omniparser"

    def __init__(self, model_dir: str | Path | None = None,
                 device: str = "auto") -> None:
        self._model_dir = Path(model_dir) if model_dir else Path.home() / ".cache" / "ozma" / "omniparser"
        self._device = device
        self._yolo = None
        self._florence = None
        self._florence_processor = None
        self._loaded = False

    def available(self) -> bool:
        try:
            import ultralytics  # noqa: F401
            import torch  # noqa: F401
            return True
        except ImportError:
            return False

    def _ensure_loaded(self) -> None:
        if self._loaded:
            return

        import torch
        from ultralytics import YOLO

        device = self._device
        if device == "auto":
            try:
                if torch.cuda.is_available():
                    # Test that CUDA actually works (driver version mismatch can cause failure)
                    torch.zeros(1, device="cuda")
                    device = "cuda"
                else:
                    device = "cpu"
            except Exception:
                device = "cpu"
                log.info("CUDA init failed, using CPU for vision")

        # Load YOLO model for UI element detection
        # OmniParser v2 uses model.pt (not best.pt)
        yolo_path = self._model_dir / "icon_detect" / "model.pt"
        if not yolo_path.exists():
            yolo_path = self._model_dir / "icon_detect" / "best.pt"
        if yolo_path.exists():
            self._yolo = YOLO(str(yolo_path))
        else:
            log.info("OmniParser YOLO model not found at %s — attempting download", yolo_path)
            try:
                self._download_models()
                yolo_path = self._model_dir / "icon_detect" / "model.pt"
                if not yolo_path.exists():
                    yolo_path = self._model_dir / "icon_detect" / "best.pt"
                self._yolo = YOLO(str(yolo_path))
            except Exception as e:
                log.warning("Failed to download OmniParser models: %s", e)
                self._yolo = YOLO("yolov8n.pt")

        # Load Florence-2 for icon description (optional, enhances descriptions)
        try:
            from transformers import AutoModelForCausalLM, AutoProcessor
            florence_path = self._model_dir / "icon_caption"
            if not florence_path.exists():
                florence_path = self._model_dir / "icon_caption_florence"  # legacy
            if florence_path.exists():
                # Processor from base model (has preprocessor_config.json),
                # weights from OmniParser fine-tune
                self._florence_processor = AutoProcessor.from_pretrained(
                    "microsoft/Florence-2-base-ft", trust_remote_code=True
                )
                self._florence = AutoModelForCausalLM.from_pretrained(
                    str(florence_path), trust_remote_code=True
                ).to(device)
                log.info("Florence-2 loaded for icon captioning")
            else:
                log.debug("Florence-2 model not found — descriptions will be basic")
        except Exception as e:
            log.debug("Florence-2 not available: %s", e)

        self._loaded = True
        self._torch_device = device
        log.info("OmniParser loaded (device=%s, florence=%s)",
                 device, self._florence is not None)

    def _download_models(self) -> None:
        """Download OmniParser model weights from HuggingFace."""
        from huggingface_hub import snapshot_download
        self._model_dir.mkdir(parents=True, exist_ok=True)

        # Download YOLO icon detection model
        snapshot_download(
            repo_id="microsoft/OmniParser-v2.0",
            local_dir=str(self._model_dir),
            allow_patterns=["icon_detect/*", "icon_caption/*"],
        )
        log.info("OmniParser models downloaded to %s", self._model_dir)

    async def detect(self, image: Any) -> VisionResult:
        import time
        t0 = time.time()

        self._ensure_loaded()
        if not self._yolo:
            return VisionResult(provider=self.name)

        import numpy as np
        from PIL import Image

        if not isinstance(image, Image.Image):
            image = Image.fromarray(np.array(image)[:, :, :3])

        w, h = image.size
        elements: list[DetectedElement] = []

        # Run YOLO detection
        results = self._yolo(image, conf=0.3, verbose=False, device=self._torch_device)

        for result in results:
            boxes = result.boxes
            if boxes is None:
                continue

            for i in range(len(boxes)):
                box = boxes[i]
                x1, y1, x2, y2 = box.xyxy[0].tolist()
                conf = float(box.conf[0])
                cls_id = int(box.cls[0])

                # Map YOLO class to element type
                # OmniParser classes: icon, text, etc.
                cls_name = result.names.get(cls_id, "unknown")
                element_type = self._map_class(cls_name)

                el = DetectedElement(
                    element_type=element_type,
                    text="",
                    x=int(x1), y=int(y1),
                    width=int(x2 - x1), height=int(y2 - y1),
                    confidence=conf,
                    clickable=element_type in ("button", "icon", "checkbox", "link", "menu_item"),
                    interactable=element_type not in ("label", "image"),
                )

                # Get description from Florence-2 if available
                if self._florence and el.width > 10 and el.height > 10:
                    crop = image.crop((int(x1), int(y1), int(x2), int(y2)))
                    el.description = self._describe_icon(crop)
                    if not el.text:
                        el.text = el.description

                elements.append(el)

        elapsed = (time.time() - t0) * 1000
        return VisionResult(elements=elements, provider=self.name, inference_ms=elapsed)

    def _describe_icon(self, crop: Any) -> str:
        """Use Florence-2 to describe a cropped UI element."""
        if not self._florence or not self._florence_processor:
            return ""
        try:
            import torch
            inputs = self._florence_processor(
                text="<CAPTION>", images=crop, return_tensors="pt"
            ).to(self._torch_device)

            with torch.no_grad():
                generated_ids = self._florence.generate(
                    **inputs, max_new_tokens=50, num_beams=3
                )
            text = self._florence_processor.batch_decode(
                generated_ids, skip_special_tokens=True
            )[0]
            return text.strip()
        except Exception:
            return ""

    @staticmethod
    def _map_class(cls_name: str) -> str:
        """Map YOLO class name to standardised element type."""
        mapping = {
            "icon": "icon", "button": "button", "text": "label",
            "input": "text_field", "checkbox": "checkbox",
            "radio": "radio", "link": "link", "menu": "menu",
            "dropdown": "dropdown", "slider": "slider",
            "toggle": "toggle", "tab": "tab",
        }
        return mapping.get(cls_name.lower(), "icon")


# ── Standalone YOLO UI provider ──────────────────────────────────────────────

class YOLOUIProvider(VisionProvider):
    """
    Standalone YOLO model fine-tuned for UI element detection.

    Lighter than OmniParser (no Florence-2), faster, but less descriptive.
    Uses ultralytics YOLOv8 with a UI-specific model.
    """

    name = "yolo_ui"

    def __init__(self, model_path: str | Path | None = None) -> None:
        self._model_path = model_path
        self._yolo = None

    def available(self) -> bool:
        try:
            import ultralytics  # noqa: F401
            return True
        except ImportError:
            return False

    async def detect(self, image: Any) -> VisionResult:
        import time
        t0 = time.time()

        if not self._yolo:
            from ultralytics import YOLO
            path = self._model_path or "yolov8n.pt"
            self._yolo = YOLO(str(path))

        results = self._yolo(image, conf=0.3, verbose=False)
        elements: list[DetectedElement] = []

        for result in results:
            boxes = result.boxes
            if boxes is None:
                continue
            for i in range(len(boxes)):
                box = boxes[i]
                x1, y1, x2, y2 = box.xyxy[0].tolist()
                conf = float(box.conf[0])
                cls_id = int(box.cls[0])
                cls_name = result.names.get(cls_id, "unknown")

                elements.append(DetectedElement(
                    element_type=cls_name,
                    text="",
                    x=int(x1), y=int(y1),
                    width=int(x2 - x1), height=int(y2 - y1),
                    confidence=conf,
                    clickable=True,
                    interactable=True,
                ))

        elapsed = (time.time() - t0) * 1000
        return VisionResult(elements=elements, provider=self.name, inference_ms=elapsed)


# ── Connect AI provider (remote) ────────────────────────────────────────────

class ConnectVisionProvider(VisionProvider):
    """
    Remote vision via Ozma Connect AI proxy.

    Sends the screenshot to Connect, which runs OmniParser or a vision
    model (Claude, GPT-4V) and returns detected elements. Metered — uses
    the user's Connect plan allocation.
    """

    name = "connect"

    def __init__(self, connect_url: str = "", api_key: str = "") -> None:
        self._url = connect_url
        self._api_key = api_key

    def available(self) -> bool:
        return bool(self._url and self._api_key)

    async def detect(self, image: Any) -> VisionResult:
        import base64, io, time, json
        import aiohttp

        t0 = time.time()

        # Encode image as JPEG
        buf = io.BytesIO()
        image.save(buf, format="JPEG", quality=80)
        img_b64 = base64.b64encode(buf.getvalue()).decode()

        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(
                    f"{self._url}/api/v1/ai/vision/detect",
                    json={"image": img_b64},
                    headers={"Authorization": f"Bearer {self._api_key}"},
                    timeout=aiohttp.ClientTimeout(total=30),
                ) as resp:
                    data = await resp.json()
        except Exception as e:
            log.debug("Connect vision failed: %s", e)
            return VisionResult(provider=self.name)

        elements = []
        for el_data in data.get("elements", []):
            elements.append(DetectedElement(
                element_type=el_data.get("type", "unknown"),
                text=el_data.get("text", ""),
                x=el_data.get("x", 0), y=el_data.get("y", 0),
                width=el_data.get("width", 0), height=el_data.get("height", 0),
                confidence=el_data.get("confidence", 0),
                description=el_data.get("description", ""),
                clickable=el_data.get("clickable", False),
                interactable=el_data.get("interactable", False),
            ))

        elapsed = (time.time() - t0) * 1000
        return VisionResult(elements=elements, provider=self.name, inference_ms=elapsed)


# ── Ollama vision provider (local AI) ────────────────────────────────────────

class OllamaVisionProvider(VisionProvider):
    """
    Local vision model via Ollama.

    Sends the screenshot to a local Ollama instance running a vision model
    (qwen2-vl, llava, minicpm-v, etc.) and asks it to identify UI elements
    with bounding boxes.

    Slower than YOLO (~2-5s) but handles novel UIs and provides descriptions.
    """

    name = "ollama"

    def __init__(self, model: str = "qwen2.5vl:7b",
                 host: str = "http://localhost:11434") -> None:
        self._model = model
        self._host = host

    def available(self) -> bool:
        try:
            import urllib.request
            req = urllib.request.Request(f"{self._host}/api/tags")
            with urllib.request.urlopen(req, timeout=2) as r:
                import json
                data = json.loads(r.read())
                models = [m["name"] for m in data.get("models", [])]
                return any(self._model.split(":")[0] in m for m in models)
        except Exception:
            return False

    async def detect(self, image: Any) -> VisionResult:
        import base64, io, time, json
        import urllib.request

        t0 = time.time()

        # Encode image
        buf = io.BytesIO()
        image.save(buf, format="JPEG", quality=80)
        img_b64 = base64.b64encode(buf.getvalue()).decode()

        prompt = (
            "Identify all clickable UI elements in this screenshot. "
            "For each element, output a JSON object with: "
            "type (button/text_field/checkbox/icon/link/menu/label/dropdown), "
            "text (visible text), "
            "bbox [x, y, width, height] in pixels. "
            "Output ONLY a JSON array, no other text."
        )

        try:
            data = json.dumps({
                "model": self._model,
                "prompt": prompt,
                "images": [img_b64],
                "stream": False,
                "options": {"temperature": 0.1},
            }).encode()

            req = urllib.request.Request(
                f"{self._host}/api/generate",
                data=data,
                headers={"Content-Type": "application/json"},
            )

            with urllib.request.urlopen(req, timeout=30) as r:
                result = json.loads(r.read())
                response_text = result.get("response", "")

            # Parse JSON from response
            elements = self._parse_elements(response_text, image.size)

        except Exception as e:
            log.debug("Ollama vision failed: %s", e)
            elements = []

        elapsed = (time.time() - t0) * 1000
        return VisionResult(elements=elements, provider=self.name, inference_ms=elapsed)

    @staticmethod
    def _parse_elements(text: str, img_size: tuple) -> list[DetectedElement]:
        """Parse JSON element list from model response."""
        import json
        elements = []

        # Find JSON array in the response
        start = text.find("[")
        end = text.rfind("]")
        if start < 0 or end < 0:
            return []

        try:
            arr = json.loads(text[start:end + 1])
        except json.JSONDecodeError:
            return []

        w, h = img_size
        for item in arr:
            if not isinstance(item, dict):
                continue
            bbox = item.get("bbox", item.get("bounding_box", [0, 0, 50, 20]))
            if len(bbox) != 4:
                continue

            # Normalise bbox (some models return 0-1 normalised, some return pixels)
            x, y, bw, bh = bbox
            if all(0 <= v <= 1 for v in bbox):
                x, y, bw, bh = int(x * w), int(y * h), int(bw * w), int(bh * h)

            el_type = item.get("type", "icon").lower()
            elements.append(DetectedElement(
                element_type=el_type,
                text=item.get("text", item.get("label", "")),
                x=int(x), y=int(y),
                width=max(int(bw), 1), height=max(int(bh), 1),
                confidence=item.get("confidence", 0.5),
                description=item.get("description", ""),
                clickable=el_type in ("button", "icon", "checkbox", "link", "menu", "dropdown"),
                interactable=el_type not in ("label", "image"),
            ))

        return elements


# ── Provider manager ─────────────────────────────────────────────────────────

class VisionProviderManager:
    """
    Manages available vision providers and selects the best one.

    Auto-detects what's available at startup:
      GPU + OmniParser weights → OmniParser
      GPU + ultralytics → YOLO UI
      Ollama running with vision model → Ollama
      Connect API key → Connect
      Always → Heuristic (built into screen_reader.py)
    """

    def __init__(self) -> None:
        self._providers: list[VisionProvider] = []
        self._active: VisionProvider | None = None

    def add(self, provider: VisionProvider) -> None:
        self._providers.append(provider)

    async def detect(self, image: Any, provider_name: str = "") -> VisionResult:
        """Run detection with the best available provider."""
        if provider_name:
            for p in self._providers:
                if p.name == provider_name and p.available():
                    return await p.detect(image)
            return VisionResult()

        # Auto-select: try providers in priority order
        for p in self._providers:
            if p.available():
                try:
                    result = await p.detect(image)
                    if result.elements:
                        return result
                except Exception as e:
                    log.debug("Provider %s failed: %s", p.name, e)

        return VisionResult()

    def list_providers(self) -> list[dict]:
        return [
            {"name": p.name, "available": p.available()}
            for p in self._providers
        ]

    @classmethod
    def create_default(cls, connect_url: str = "", connect_key: str = "",
                        omniparser_dir: str = "",
                        omniparser_server: str = "") -> "VisionProviderManager":
        """Create manager with all default providers."""
        mgr = cls()

        # OmniParser server sidecar (highest priority — best quality, separate process)
        if omniparser_server:
            mgr.add(OmniParserServerProvider(omniparser_server))
        else:
            # Auto-detect local OmniParser server on default port
            mgr.add(OmniParserServerProvider("http://localhost:8000"))

        # OmniParser in-process (if server not available, try loading models directly)
        omni = OmniParserProvider(model_dir=omniparser_dir or None)
        mgr.add(omni)

        # Standalone YOLO
        mgr.add(YOLOUIProvider())

        # Ollama local vision
        mgr.add(OllamaVisionProvider())

        # Connect remote
        if connect_url and connect_key:
            mgr.add(ConnectVisionProvider(connect_url, connect_key))

        return mgr


# ── OmniParser server sidecar ────────────────────────────────────────────────

class OmniParserServerProvider(VisionProvider):
    """
    OmniParser running as a FastAPI sidecar server.

    This is the recommended production path — keeps heavy ML dependencies
    (torch, ultralytics, transformers, easyocr) in a separate process.

    Start the server:
      cd OmniParser/omnitool/omniparserserver
      python -m omniparserserver --som_model_path ../../weights/icon_detect/model.pt \\
        --caption_model_path ../../weights/icon_caption_florence --port 8000

    Or with ozma:
      python3 controller/setup_vision.py --start-server
    """

    name = "omniparser_server"

    def __init__(self, url: str = "http://localhost:8000") -> None:
        self._url = url.rstrip("/")
        self._checked = False
        self._available = False

    def available(self) -> bool:
        if self._checked:
            return self._available
        self._checked = True
        try:
            import urllib.request
            req = urllib.request.Request(f"{self._url}/probe/")
            with urllib.request.urlopen(req, timeout=2) as r:
                self._available = r.status == 200
        except Exception:
            self._available = False
        return self._available

    async def detect(self, image: Any) -> VisionResult:
        import base64, io, time, json
        import aiohttp

        t0 = time.time()

        # Encode image as base64 PNG
        buf = io.BytesIO()
        image.save(buf, format="PNG")
        img_b64 = base64.b64encode(buf.getvalue()).decode()

        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(
                    f"{self._url}/parse/",
                    json={"base64_image": img_b64},
                    timeout=aiohttp.ClientTimeout(total=30),
                ) as resp:
                    data = await resp.json()
        except Exception as e:
            log.debug("OmniParser server error: %s", e)
            return VisionResult(provider=self.name)

        elements = []
        w, h = image.size

        for item in data.get("parsed_content_list", []):
            bbox = item.get("bbox", [0, 0, 0, 0])
            # OmniParser returns normalised 0-1 xyxy coordinates
            x1 = int(bbox[0] * w)
            y1 = int(bbox[1] * h)
            x2 = int(bbox[2] * w)
            y2 = int(bbox[3] * h)

            el_type = "icon" if item.get("interactivity") else "label"
            if item.get("type") == "text":
                el_type = "label"

            elements.append(DetectedElement(
                element_type=el_type,
                text=item.get("content", ""),
                x=x1, y=y1,
                width=max(x2 - x1, 1), height=max(y2 - y1, 1),
                confidence=0.5,  # OmniParser doesn't expose confidence
                description=item.get("content", ""),
                clickable=item.get("interactivity", False),
                interactable=item.get("interactivity", False),
            ))

        elapsed = (time.time() - t0) * 1000
        server_latency = data.get("latency", 0)
        if server_latency:
            log.debug("OmniParser server latency: %.1fms (total %.1fms)",
                      server_latency * 1000, elapsed)

        return VisionResult(elements=elements, provider=self.name, inference_ms=elapsed)
